build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

matrix:
    fast_finish: true

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - conda install pip scipy numpy scikit-learn=0.19 -y -q
  - conda install pytest pytest-cov -y -q
  - conda install nose -y -q  # FIXME: remove this line when using sklearn > 0.19
  - pip install .

test_script:
  - mkdir for_test
  - cd for_test
  - pytest --pyargs --cov-report term-missing --cov=drforest
