name: Build

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      #- name: Install Armadillo
      #  run: sudo apt-get install libarmadillo-dev; ls /usr/include/armadillo

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_SKIP: cp27-* cp35-*

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
